name: Build Exploit
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Compile Exploit
        run: msbuild "Windows_AFD_LPE_CVE-2023-21768.sln" /p:Configuration=Release /p:Platform=x64

      - name: Upload Finished Payload
        uses: actions/upload-artifact@v4
        with:
          name: AfdBinary
          path: "**/Release/*.exe"
          if-no-files-found: error
